version: '3.8'
services:
  worker:
    build: ./fantasticoweather
    container_name: fantasticoweather
    ports:
      - '3000:3000'
    volumes:
      - ./fantasticoweather/:/fantasticoweather/
      - /fantasticoweather/node_modules
    stdin_open: true
    tty: true
